spring:
  application:
    name: zentask

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver   # ðŸ”¥ THIS LINE FIXES IT

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

zentask:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000
